In [100]:
#1.4장 데이터 핸들링

In [101]:
#0 pandas

In [102]:
import pandas as pd

In [103]:
#1 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [104]:
#1.1 특정 파일의 위치에서 가져오기
titanic_df=pd.read_csv(r'C:\Users\chb12\Desktop\titanic_train.csv.csv')
titanic_df.head(3)

   PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292   NaN        Q
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000   NaN        S
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875   NaN        Q

In [105]:
#1.2 코드가 현재 있는 위치에서 data 가져오기
titanic_df=pd.read_csv('titanic_train.csv')
print('titanic 변수 type:', type(titanic_df))
titanic_df
#맨 처음 로우가 칼럼명으로 설정

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0              1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2              3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3              4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4              5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S
..           ...       ...     ...             ...     ...   ...    ...    ...             ...      ...   ...      ...
886          887         0       2  Montvila, R...    male  27.0      0      0          211536  13.0000   NaN        S
887          888         1       1  Graham, Mis...  female  19.0      0      0          112053  30.0000   B42        S
888          889         0       3  Johnston, M...  female   NaN      1      2      W./C. 6607  23.4500   NaN        S
889          890         1       1  Behr, Mr. K...    male  26.0      0      0          111369  30.0000  C148        C
890          891         0       3  Dooley, Mr....    male  32.0      0      0          370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [106]:
#1.3 DataFrame의 행과 열 크기_shape 변수
print('FataFrame 크기: ', titanic_df.shape)

FataFrame 크기:  (891, 12)

In [107]:
#1.4 Data조회 방법_메서드(method)

In [108]:
#1.4.1 info : 데이터 건수, 타입, Null 건수
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [109]:
#1.4.2 describe : 숫자형 데이터의 분석
titanic_df.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [110]:
#1.4.3 Value counts : 데이터의 분포도
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
#pclass : 객실 등급

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [111]:
#1.4.4 series 객체로 반환
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [112]:
#(1) pclass 데이터 _ ['Pclass']
titanic_pclass.head()
#5개 데이터만 추출
#왼쪽(순차값_인덱스값) 오른쪽(칼럼의 데이터값)

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [113]:
#(2) pclass value_counts 데이터 _ ['Pclass'].value_counts()
calue_counts=titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)
#왼쪽(데이터 인덱스값) 오른쪽(value counts의 데이터값)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [114]:
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
#value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))
#데이터가 책과 달라서 Null 데이터가 없음?

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [115]:
#2 DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [116]:
#2.1 (1)넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기
##string(문자열) ('col1') vs 리스트 ['col1']

import numpy as np

col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape:', array1.shape)

#리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
#넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

#결과: list로 만든 DataFrame(pandas) vs ndarray로 만든 DataFrame(numpy)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [117]:
#2.1 (2)넘파이 ndarray, 리스트를 DataFrame으로 변환하기

##3개의 칼럼명이 필요
col_name2=['col1', 'col2', 'col3']

## 2행*3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1,2,3],[11,12,13]]
array2=np.array(list2)
print('array2 shape:', array2.shape)
df_list2=pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2=pd.DataFrame(list2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_list2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [118]:
#2.2 딕셔너리를 DataFrame으로 변환하기
## key(키) : 칼럼명_문자열, value(값) : 칼럼 데이터_list or ndarry

dict={'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

In [119]:
#2.3 DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기 _ .values

In [120]:
#2.3.1 DataFrame을 ndarray로 변환
array3=df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [121]:
#2.3.2 DataFrame을 list로 변환
list3 = df_dict.values.tolist()
print('df_fict.values.tolist() 타입:', type(list3))
print(list3)

df_fict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

In [122]:
#2.3.3 DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict()타입:', type(dict3))
print(dict3)

 df_dict.to_dict()타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [123]:
#3 DataFrame의 칼럼 데이터 세트 생성과 수정

In [124]:
#3.1 열 일괄적 수정 _ [ ] 연산자 사용
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

In [125]:
#3.2 (1)새로운 칼럼 series 생성
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [126]:
#3.2 (2)새로운 칼럼 series 생성
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] +100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [127]:
#4 DataFrame 데이터 삭제 _ Drop()
#DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

In [128]:
#4.1 axis
titanic_drop_df=titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

In [129]:
titanic_df.head(3)
#여전히 남아있는 'Age_0' 칼럼 : inplace를 Flase로 설정했기 때문 (기제하지 않으면 자동으로 False)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

In [130]:
#4.2 inplace_True
drop_result=titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)
#앞의 결과와 달리 적용된 것을 확인할 수 있다!!

inplace=True로 drop 후 반환된 값: None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [131]:
#예제
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('### before axis 0 drop ###')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('XXX after axis 0 drop ####')
print(titanic_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
XXX after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

In [132]:
#5 index 객체

In [133]:
#5.1 DataFrame에서 index객체 추출

##원본 파일 다시 로딩
titanic_df=pd.read_csv('titanic_train.csv')
##Index 객체 추출
indexes=titanic_df.index
print(indexes)
#Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [134]:
#5.2 Index로 단일 값 반환 및 슬라이싱 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [135]:
#5.3 Index 객체 변경은 불가능
indexes[0] = 5

TypeError: Index does not support mutable operations

In [136]:
#5.4 series객체에 index객체가 포함되기는 하지만 연산할 때 index는 제외 why? 단순히 식별용이기 때문에
series_fair= titanic_df['Fare']
print('Fair Series max값:', series_fair.max())
print('Fair Series sum값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head(3))

Fair Series max값: 512.3292
Fair Series sum값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [137]:
#5.5 새로운 index를 할당하고 싶은 경우 _ reset_index
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)
#index앞에 새로운 index가 생김

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [138]:
#5.6 index를 reset 함으로써 series에서 dataframe으로 전환
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

# 6 데이터 셀렉션 및 필터링

# 데이터 추출 방법: 넘파이 vs 판다스

*데이터의 저장 방식*
- 넘파이: ndarry(n차원)
> 수치 연산에 강함 : 위치
- 판다스: Series(1차원), **DataFrame(2차원 이상)**
> 데이터 분석에 강함 : 위치 + 명칭
>> 수치 연산에는 약함(불편?)

**23pg. (Numpy_ndarray) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱**
1. 특정한 데티어만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. 슬라이싱: ':' 리스트
3. 팬시 인덱싱: 인덱스 집합
4. 불린 인덱싱: 특정 조건에 해당 여부 > True/False
- 1번의 경우 특정 위치, 2번은 리스트, 3번은 인덱스의 집합을 불러오기

**62pg. (Pandas_DataFrame) 데이터 셀렉션 및 필터링**
1. DataFrame의 [ ]연산자 : (위치,명칭) 칼럼명 기반
> ['칼럼명']: 1개 열 / [['칼럼명', '칼럼명']]: 2개 이상의 열 

2. DataFrame iloc [ ] 연산자 : 위치 기반 인덱싱
> data_df.iloc[0,0]

3. DataFrame loc[ ] 연산자 : 명칭 기반 인덱싱
> data_df.loc['one', 'Name']
- -----------------------------------------

4. 불린 인덱싱 : 특정 조건에 해당 여부 > True/False

# 6.1. DataFrame의 [ ]연산자 [정리]
1. 칼럼명: 열(칼럼_column)으로 찾음 (일반적인 case)

2. 숫자(일반): 일반적으로 오류 발생
3. 숫자(예외1): 슬라이싱':' > 행(row)로 찾음
4. 숫자(예외2): 불린 인덱싱

#Tip. 일반적으로 사용하지 않는 것이 좋다!

In [139]:
#6.1.1 DataFrame의 []연산자 _ [' '](O) [](X)

##['칼럼명'] 으로 사용 / [칼람명] (X)
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass']. head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
print('[] 안에 숫자 index는 keyerror 오류 발생:\n', titanic_df[0])

#에러가 발생하는 이유: DataFrame뒤의 []에는 칼럼명을 지정해줘야 하는데 데이터를 넣었기 때문

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [ ]:
#6.1.2 (1) DataFrame[ ]에 칼럼명이 아닌 숫자를 넣어도 되는 경우 
titanic_df[0:2] 

#slicing ':'

In [ ]:
#6.1.3 (2) [ ]에 칼럼명이 아닌 숫자를 넣어도 되는 경우 
#불린(Boolean) 인덱싱 표현도 가능 : 보통 데이터 셀력션할 때 많이 사용
titanic_df[titanic_df['Pclass']==3].head(3)

# 6.2 iloc[ ] _ 위치기반 인덱싱

1. 일반적인 경우
- data_df.iloc[0,0]
  
2. 오류가 발생하는 경우 : 위치가 아닌 명칭을 넣었을 경우
3. '-1'의 역할 : 맨 뒤에서부터 세기

In [140]:
#6.2.1 DataFrame iloc[ ] 연산자 _ 위치 기반 인덱싱
data={'Name': ['A', 'B','C','D'],
      'Year': ['11','12','13','14'],
      'Gender': ['Male','Female','Male','Male']
     }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

      Name Year  Gender
one      A   11    Male
two      B   12  Female
three    C   13    Male
four     D   14    Male

In [141]:
data_df.iloc[0,0]

'A'

In [142]:
#6.2.2 오류가 발생하는 경우 _ 위치가 아닌 다른 입력을 하였을 경우
data_df.iloc[0,'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [ ]:
#6.2.3 iloc[ ] 에서 '-1'을 쓰는 경우 : 맨 뒤에서부터 세기
print("\n 맨 마지막 칼럼 데이터 [:,-1] \n", data_df.iloc[:,-1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]\n", data_df.iloc[:,:-1])

# 6.3 loc[ ] _ 명칭기반 인덱싱

1. 일반적인 경우
data_df.loc['one', 'Name']
  
2. 오류가 발생하는 경우 : 명칭이 아닌 위치를 넣었을 경우
3. ':'의 의미: 시작값~종료값

In [76]:
#6.3.1 loc[ ] _ 명칭 기반 인덱싱
data_df.loc['one', 'Name']

'A'

In [77]:
#6.3.2 명칭이 아닌 다른 입력을 하였을 경우
data_df.loc[0,'Name']

KeyError: 0

In [ ]:
#6.3.3 loc[ ]에서 ':'의 의미
# 일반적으로 시작값 ~ 종료값 -1인데 loc[ ]에서는 시작값~종료값이다!
print('위치기반 iloc slicing\n', data_df.iloc[0:1,0],'\n')
print('위치기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

# 6.4 불린 인덱싱

1. 일반적인 경우: 넘파이와 유사하게 사용
2. and(&) / or(|) / not(~) 와 함께 사용 가능

In [78]:
#6.4.1 불린 인덱싱 _ 조건에 맞는 데이터만 쏘옥! 매우 유용한 TOOL
titanic_df=pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] >60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Pclass            Name     Sex   Age  SibSp  Parch    Ticket      Fare           Cabin Embarked
2            894       2  Myles, Mr. ...    male  62.0      0      0    240276    9.6875             NaN        Q
13           905       2  Howard, Mr....    male  63.0      1      0     24065   26.0000             NaN        S
81           973       1  Straus, Mr....    male  67.0      1      0  PC 17483  221.7792         C55 C57        S
96           988       1  Cavendish, ...  female  76.0      1      0     19877   78.8500             C46        S
114         1006       1  Straus, Mrs...  female  63.0      1      0  PC 17483  221.7792         C55 C57        S
142         1034       1  Ryerson, Mr...    male  61.0      1      3  PC 17608  262.3750  B57 B59 B63...        C
152         1044       3  Storey, Mr....    male  60.5      0      0      3701       NaN             NaN        S
179         1071       1  Compton, Mr...  female  64.0      0      2  PC 17756   83.1583             E45        C
193         1085       2  Lingane, Mr...    male  61.0      0      0    235509   12.3500             NaN        Q
236         1128       1  Warren, Mr....    male  64.0      1      0    110813   75.2500             D37        C
305         1197       1  Crosby, Mrs...  female  64.0      1      1    112901   26.5500             B26        S

In [79]:
#6.4.2  
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

              Name   Age
2   Myles, Mr. ...  62.0
13  Howard, Mr....  63.0
81  Straus, Mr....  67.0

In [80]:
#6.4.3 and(&) / or(|) / not(~) 과 함께 응용도 가능!
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&
    (titanic_df['Sex']=='female')]

     PassengerId  Pclass            Name     Sex   Age  SibSp  Parch    Ticket      Fare    Cabin Embarked
96           988       1  Cavendish, ...  female  76.0      1      0     19877   78.8500      C46        S
114         1006       1  Straus, Mrs...  female  63.0      1      0  PC 17483  221.7792  C55 C57        S
179         1071       1  Compton, Mr...  female  64.0      0      2  PC 17756   83.1583      E45        C
305         1197       1  Crosby, Mrs...  female  64.0      1      1    112901   26.5500      B26        S

# 7 정렬, Aggregation함수, GroupBy 적용

# 7.1. 정렬

**33pg. 넘파이 - sort()와 argsort()**
- sort() : 값 자체를 정렬 
- argsort() : 값의 인덱스를 정렬
- 1 2 3
- 10 13 12


**73pg. 판다스 - sort_values()**
- sort_values() : 2차원이기에... 뒤에서 설명

In [81]:
#7.1.1 DataFrame, Series의 정렬 - sort_values()
#by에 특정 칼럼을 입력하면 "그것을 기준으로" 정렬 실행: 오름차순 - True / 내림차순 - False 
#: 이것도 inplace로 설정해야함 (기본값이 False)
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare  Cabin Embarked
392         1284       3  Abbott, Mas...    male  13.0      0      2  C.A. 2673  20.25    NaN        S
345         1237       3  Abelseth, M...  female  16.0      0      0     348125   7.65    NaN        S
57           949       3  Abelseth, M...    male  25.0      0      0     348122   7.65  F G63        S

In [82]:
#7.1.2 Pclass와 Name을 내림차순으로 
titanic_sorted=titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)
# 2개 이상의 기준이 있을 경우, 먼저 온 것부터 내림차순 진행

     PassengerId  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
192         1084       3  van Billiar...  male  11.5      1      1  A/5. 851  14.5   NaN        S
344         1236       3  van Billiar...  male   NaN      1      1  A/5. 851  14.5   NaN        S
260         1152       3  de Messemae...  male  36.5      1      0    345572  17.4   NaN        S

# 7.2. Aggregation

-넘파이: sum / mean / max,min ~

-판다스: count()

In [83]:
#7.2.1 Aggregation함수 적용
#모든 칼럼에 적용, 단 Null은 반영X
titanic_df.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [84]:
#7.2.2 특정 칼럼만 적용하고 싶은 경우
titanic_df[['Age','Fare']].mean
#Nan은 포함X

<bound method DataFrame.mean of       Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
413   NaN    8.0500
414  39.0  108.9000
415  38.5    7.2500
416   NaN    8.0500
417   NaN   22.3583

[418 rows x 2 columns]>

# 7.3. Groupby (numpy에는 없는 놈)
> 새로운 기준으로 재편성 : 그 기준이 곧 '칼럼'

1. titanic_df.groupby(by='Pclass')
> Pclass를 기준으로 재편성

2. titanic_df.groupby('Pclass').count()
> 재편성 기준으로 각각의 칼럼 총계

3. titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
> 재편성한 것들 중에서 특정 칼럼만 추출

4. groupby('Pclass')['Age'].agg([max,min])
> 추출한 칼럼들의 max, min

In [85]:
#7.3.1 groupby()적용 - Numpy에 없음
#groupby란? 새로운 그룹으로 묶어주는 것
#: 데이터를 새로운 기준으로 "재편성"
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))
#Pclass(1,2,3)로 그룹지어준 것 (Pclass = 1인 그룹...)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [86]:
#7.3.2 특정 칼럼에 대해서 그룹핑을 요구하는 경우에는 대상 칼럼을 기준으로 나머지 변수들에 aggregation 함수를 적용함
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               107   107  107   98    107    107     107   107     80       107
2                93    93   93   88     93     93      93    93      7        93
3               218   218  218  146    218    218     218   217      4       218

In [143]:
#7.3.3 앞서 특정칼럼을 기준으로 나열한 것에서 몇가지만 빼오기
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [ ]:
#7.3.4 앞서 뺴온 것에서 max, min 구하기
titanic_df.groupby('Pclass')['Age'].agg([max,min])

In [88]:
#7.3.5 DataFrame groupby() 예제
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       76.0     51  94.280297
2       63.0     35  22.202104
3       60.5    101  12.459678

# 8. 결손 데이터 (numpy에는 없는 놈)
- NaN을 어떻게 다룰 것인가

1. (1) isna()
> NaN 인지 확인
>> True/False 로 알려주기

2. (2) isna().sum()
> 각 칼럼에서 NaN의 개수 확인

3. fillna()
> 결손 데이터 새로운 것으로 채우기

In [89]:
#8.1.1 isna()로 결손 데이터 여부 확인
#NaN인지 아닌지 True/False로 알려줌
titanic_df.isna().head(3)

   PassengerId  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False   False  False  False  False  False  False   False  False   True     False
1        False   False  False  False  False  False  False   False  False   True     False
2        False   False  False  False  False  False  False   False  False   True     False

In [90]:
#8.1.2 결손의 갯수를 알고 싶은 경우
titanic_df.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [91]:
#8.2.1 fillna()로 결손 데이터 대체하기
#결손 데이터를 편리하게 다른 값으로 대체해줌
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)
#inplace=True로 적용해야지만 반영된다!!

   PassengerId  Pclass            Name     Sex   Age  SibSp  Parch  Ticket    Fare Cabin Embarked
0          892       3  Kelly, Mr. ...    male  34.5      0      0  330911  7.8292  C000        Q
1          893       3  Wilkes, Mrs...  female  47.0      1      0  363272  7.0000  C000        S
2          894       2  Myles, Mr. ...    male  62.0      0      0  240276  9.6875  C000        Q

In [92]:
#8.2.2 Age의 결손 데이터를 평균 나이로(Aggregation의 데이터를 실시간으로 사용), Embarked에는 S로 반영
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df

     PassengerId  Pclass            Name     Sex       Age  SibSp  Parch          Ticket      Fare Cabin Embarked
0            892       3  Kelly, Mr. ...    male  34.50000      0      0          330911    7.8292  C000        Q
1            893       3  Wilkes, Mrs...  female  47.00000      1      0          363272    7.0000  C000        S
2            894       2  Myles, Mr. ...    male  62.00000      0      0          240276    9.6875  C000        Q
3            895       3  Wirz, Mr. A...    male  27.00000      0      0          315154    8.6625  C000        S
4            896       3  Hirvonen, M...  female  22.00000      1      1         3101298   12.2875  C000        S
..           ...     ...             ...     ...       ...    ...    ...             ...       ...   ...      ...
413         1305       3  Spector, Mr...    male  30.27259      0      0       A.5. 3236    8.0500  C000        S
414         1306       1  Oliva y Oca...  female  39.00000      0      0        PC 17758  108.9000  C105        C
415         1307       3  Saether, Mr...    male  38.50000      0      0  SOTON/O.Q. ...    7.2500  C000        S
416         1308       3  Ware, Mr. F...    male  30.27259      0      0          359309    8.0500  C000        S
417         1309       3  Peter, Mast...    male  30.27259      1      1            2668   22.3583  C000        C

[418 rows x 11 columns]

# 9 apply lambda 식으로 데이터 가공

# 9. 데이터 가공하기
> pandas의 무기 : 사실 데이터 분석을 하기 위해서는 데이터 가공이 필수적

***return(python 자체 언어) <-> lambda(pandas)***
> lambda x : x**2
>> 입력값 : 계산 과정

In [93]:
#9.1.1 return을 사용하는 경우
def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [94]:
#9.1.2 lambda를 쓰는 경우~!
lambda_square = lambda x : x**2
print('3의 제곱은:', lambda_square(3))
# ':'으로 입력인자와 계산식을 분리시켜줌

3의 제곱은: 9

In [95]:
#9.1.3 map가 병합하는 경우
a=[1,2,3]
squares = map(lambda x : x**2, a)
list(squares)
#map: 하나씩 자동으로 넣어주기

[1, 4, 9]

In [96]:
#9.2.1 DataFrame과 lambda의 병합 - 2차원에 적용!
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

             Name  Name_len
0  Kelly, Mr. ...        16
1  Wilkes, Mrs...        32
2  Myles, Mr. ...        25

In [97]:
#9.2.2 lambda에 if / else절을 사용
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

    Age Child_Adult
0  34.5       Adult
1  47.0       Adult
2  62.0       Adult
3  27.0       Adult
4  22.0       Adult
5  14.0       Child
6  30.0       Adult
7  26.0       Adult

In [98]:
#9.2.3 lambda에서는 else if는 지원X >> 다음과 같이 귀찮게 해야함ㅋㅋ
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60
                                                                                  else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      375
Child       32
Elderly     11
Name: count, dtype: int64