In [3]:
import pandas as pd

In [5]:
titanic_df = pd.read_csv(r"C:\Users\yhseo\Downloads\titanic_train.csv")
print(type(titanic_df))
titanic_df

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
titanic_df.head(3) # dataframe의 맨앞 3개의 로우를 반환

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [9]:
titanic_df.shape # dataframe의 행과 열을 튜플형태로 반환, dataframe의 크기를 알 수 있음

(891, 12)

In [11]:
titanic_df.info() # 총 데이터 건수와 데이터타입, null 건수를 알 수 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
titanic_df.describe() # 칼럼별 숫자형 데이터값의 n_percentile 분포도, 평균값, 최댓값, 최솟값 나타냄

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
# count 는 NotNULL인 데이터 건수, mean은 전체 데이터의 평균값, std는 표준편차
# 카테고리 칼럼: 특정 범주에 속한 값을 코드화한 칼럼 (ex. 남자는 1, 여자는 2)

In [27]:
value_counts = titanic_df['Pclass'].value_counts() # 지정된 칼럼의 데이터값 건수, 기본적으로 null값을 무시함
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [23]:
# Series 는 index와 단 하나의 칼럼으로 구성된 데이터 세트

In [25]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))
titanic_pclass.head()

<class 'pandas.core.series.Series'>

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [33]:
titanic_df.shape[0] # 타이타닉 데이터 건수
# value_counts()는 디폴트로 dropna=True 이므로 value_counts(dropna=True)와 동일
titanic_df['Embarked'].value_counts() #기본설정
titanic_df['Embarked'].value_counts(dropna=False) #null값 포함하여 적용

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [43]:
import numpy as np

col_name=['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print(array1.shape)
# 리스트를 이용해 Dataframe 생성
df_list1 = pd.DataFrame(list1,columns=col_name)
print(df_list1)
# 넘파이 ndarray를 이용해 Dataframe 생성
df_array1 = pd.DataFrame(array1, columns=col_name)
print(df_array1)

(3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3

In [85]:
# 2차원 데이터를 기반으로 dataframe 생성
# 2행 3열 형태의 리스트와 ndarray -> 3개의 칼럼명이 필요함
col_name2 = ['col1','col2','col3']

# 2행3열 형태의 리스트와 ndarray 생성한 뒤 이를 dataframe으로 변환
list2 = [[1,2,3],[11,12,13]]
array2 = np.array(list2)
print(array2.shape)
df_list2 = pd.DataFrame(list2,columns=col_name2)
print(df_list2)
df_array2 = pd.DataFrame(array2,columns=col_name2)
print(df_array2)

(2, 3)
   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13

In [87]:
# 딕셔너리를 dataframe으로 변환
# 딕셔너리의 키는 칼럼명으로, 딕셔너리의 값은 키에 해당하는 칼럼데이터로 변환(value는 리스트 혹은 ndarray 칼럼데이터로 매핑)
dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33

In [89]:
# Dataframe을 ndarray로 변환
array3 = df_dict.values
print(type(array3),array3.shape)
print(array3)

<class 'numpy.ndarray'> (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [101]:
# dataframe을 리스트로 변환 , values로 얻은 ndarray에 tolist()를 호출
list3 = df_dict.values.tolist()
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list') # 딕셔너리이 값이 리스트 형으로 반환
print(dict3)

[[1, 2, 3], [11, 22, 33]]
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [113]:
# dataframe의 칼럼 데이터 세트 생성과 수정
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      0
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q      0

In [115]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0      350.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      0      350.0          1
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q      0        NaN          1

In [117]:
titanic_df['Age_by_10'] = titanic_df['Age']*10+100
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0      450.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      0      450.0          1
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q      0        NaN          1

In [119]:
# drop() : 데이터 삭제
# axis=0 은 로우방향, axis=1은 칼럼방향
# drop 메서드에 axis=0을 입력하면 특정 로우를 드롭하겠다는 의미, 주로 axis=1, 이상치데이터를 삭제하는 경우에는 axis=0
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      450.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      450.0          1
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q        NaN          1

In [121]:
# inplace의 디폴트값은 false, 따라서 아직 원본 dataframe의 age_0컬럼이 삭제되지 않았음
titanic_df.head(3) # 아직 age_0 존재
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'], axis=1, inplace=True) # 이때 자기자신을 객체로 할당하면 변수를 아예 None으로 만들어버림
print(drop_result)
titanic_df.head(3)

None

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

In [135]:
# 로우 삭제
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('### before axis 0 drop ###')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('### after axis 0 drop ###')
print(titanic_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

In [137]:
# 원본파일 다시 로딩
titanic_df = pd.read_csv(r"C:\Users\yhseo\Downloads\titanic_train.csv")
# index 객체 추출
indexes = titanic_df.index
print(indexes)
# index 객체를 실제 값 array로 변환
print('index 객체 array 값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [141]:
# index 객체는 식별성 데이터를 1차원 어레이로 가지고 있음. ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능
type(indexes.values)
indexes[5]
indexes[:5].values

array([0, 1, 2, 3, 4], dtype=int64)

In [143]:
# series 객체는 index 객체를 포함하지만 연산함수 적용에서는 제외(오직 식별용으로만 사용됨)
series_fair = titanic_df['Fare']
(series_fair +3).head(3)

0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [153]:
titanic_reset_df = titanic_df.reset_index(inplace=False) # 기존 index를 새로운 칼럼명으로 추가하고 새롭게 인덱스를 연속 숫자형으로 할당
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [155]:
print('### before reset_indexes ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

new_value_counts = value_counts.reset_index(inplace=False)
print('### after reset_indexes ###')
print(new_value_counts)

### before reset_indexes ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
### after reset_indexes ###
   Pclass  count
0       3    491
1       1    216
2       2    184

In [159]:
# 단일 컬럼데이터 추출
print(titanic_df['Pclass'].head(3))
# 여러 컬럼데이터 추출
print(titanic_df[['Survived','Pclass']].head(3))

0    3
1    1
2    3
Name: Pclass, dtype: int64
   Survived  Pclass
0         0       3
1         1       1
2         1       3

In [161]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [163]:
# boolean indexing
titanic_df[titanic_df['Pclass']==3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

In [165]:
data = {'Name': ['chulmin','eunkyung','jinwoong','soobeom'],
        'Year': [2011,2016,2015,2015],
        'Gender': ['male','female','male','male']}
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     chulmin  2011    male
two    eunkyung  2016  female
three  jinwoong  2015    male
four    soobeom  2015    male

In [167]:
data_df.iloc[0,0]

'chulmin'

In [171]:
# 맨마지막 칼럼 데이터 [:,-1]
print(data_df.iloc[:,-1])
# 맨마지막 칼럼을 제외한 모든 데이터 [:,:-1]
print(data_df.iloc[:,:-1])

one        male
two      female
three      male
four       male
Name: Gender, dtype: object
           Name  Year
one     chulmin  2011
two    eunkyung  2016
three  jinwoong  2015
four    soobeom  2015

In [177]:
data_df.loc['one','Name'] # iloc는 정수슬라이싱, loc는 label기반으로 데이터 추출

'chulmin'

In [179]:
# loc에서 슬라이싱 기호 적용하면 종료값-1 이 아니라 종료값까지 포함
# 위치기반 iloc slicing
print(data_df.iloc[0:1,0])
# 명칭기반 loc slicing
print(data_df.loc['one':'two','Name'])

one    chulmin
Name: Name, dtype: object
one     chulmin
two    eunkyung
Name: Name, dtype: object

In [183]:
titanic_df = pd.read_csv(r"C:\Users\yhseo\Downloads\titanic_train.csv")
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(titanic_boolean)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [185]:
# 60세 이상인 승객의 나이와 이름 추출
# 칼럼이 두개 이상이므로 [[]] 사용
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [191]:
# loc 이용
# ['Name','Age'] 는 칼럼 위치에 놓여야함
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [193]:
# 나이가 60세 이상이고 선실등급이 1등급이며 성별이 여성인 승객 추출
# 개별 조건은 ()로 묶고, 복합연산자를 사용
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [195]:
# 개별 조건을 변수에 할당하고 결합해도됨
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [197]:
# ascending=True : 오름차순 정렬, False는 내림차순
# inplace=False 로 설정하면(기본) 호출한 dataframe은 그대로 유지하면서 정렬된 dataframe을 결과로 반환, True 는 호출한 dataframe의 정렬결과를 그대로 적용
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [199]:
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

In [201]:
titanic_df.count() #null값 반영하지 않은 모든 칼럼에 count결과를 반환

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [203]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [207]:
titanic_groupby = titanic_df.groupby(by='Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [209]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby #passengerid 와 survived 칼럼에만 count 수행

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [213]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

C:\Users\yhseo\AppData\Local\Temp\ipykernel_19776\414103430.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
C:\Users\yhseo\AppData\Local\Temp\ipykernel_19776\414103430.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [215]:
agg_format = {'Age':'max','SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [9]:
# isna() 로 결손데이터 여부 확인 / NaN 인지 아닌지
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

In [11]:
# sum함수를 추가하면 true는 1, false는 0으로 변환되므로 결손데이터의 개수를 구할 수 있음
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [17]:
# fillna()로 결손데이터 대체하기
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000') # cabin 칼럼의 nan 값을 C000으로 대체
titanic_df.head(3) # 이때 inplace=True를 설정해야 실제데이터 세트값이 변경됨

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C000,S

In [19]:
# age 칼럼의 nan 값을 평균나이로, embarked 칼럼의 nan 값을 s 로 대체해 모든 결손데이터 처리
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [21]:
def get_square(a):
    return a**2
get_square(3)

9

In [23]:
# lambda 식으로 변환
lambda_square = lambda x : x**2
lambda_square(3)

9

In [29]:
# 여러개 값을 입력인자로 사용해야할 경우에는 보통 map()함수 결합해서 사용
a = [1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [31]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

                                                Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [35]:
# 나이가 15세 미만이면 child, 그렇지 않으면 adult로 구분
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)
# if 식보다 반환 값을 먼저 기술, else if는 안됨

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [37]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [39]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
    cat = ''
    if age <= 5 : cat = 'Baby'
    elif age <= 12 : cat = 'Child'
    elif age <= 18 : cat = 'Teenager'
    elif age <= 25 : cat = 'Student'
    elif age <= 35 : cat = 'Young Adult'
    elif age <= 60 : cat = 'Adult'
    else : cat = 'Elderly'
    return cat

# lambda 식 위에서 생성한 get_category()함수를 반환값으로 지정
# get_category(x)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult