In [1]:
import pandas as pd

df=pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
#남녀 수
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [3]:
#gender 별 평균 수학 점수
df.groupby('gender')['math score'].mean()

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

In [4]:
#수학 점수 가장 높은 학생
df.loc[df['math score'].idxmax()]

gender                                       male
race/ethnicity                            group E
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                 completed
math score                                    100
reading score                                 100
writing score                                  93
Name: 149, dtype: object

In [6]:
#reading score>90인 학생
high_reading=df[df['reading score']>90]
high_reading

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
102,female,group D,associate's degree,standard,none,85,91,89
106,female,group D,master's degree,standard,none,87,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100
...,...,...,...,...,...,...,...,...
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
970,female,group D,bachelor's degree,standard,none,89,100,100
979,female,group C,associate's degree,standard,none,91,95,94
995,female,group E,master's degree,standard,completed,88,99,95