### Pandas 시작- 파일을 DataFrame 로딩, 기본 API

In [1]:
# pandas 모듈을 import를 통해 불러오기
import pandas as pd

In [2]:
#csv 파일을 불러와 titanic_df라는 변수에 저장
titanic_df = pd.read_csv(r"C:\Users\Sanghyeon\CUAI_Basic_study\titanic_train.csv")
#type() 함수를 사용하여 titanic_df 변수의 데이터 타입을 확인하고 출력한다.
print('titanic 변수 type:',type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
#데이터프레임의 상위 3개 행만 화면에 출력하여 데이터가 잘 들어왔는지 보는것

titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
#.shape를 통해 데이터프레임의 행(row)과 열(column)의 개수를 튜플(tuple) 형태로 반환
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)

In [5]:
#데이터프레임의  요약 정보를 출력함
#행과 열의 개수, 각 열의 이름, 비어있지 않은 데이터의 개수
#데이터 타입을 한번에 보여줌
#이때 nnon-null count에 있는수로 결측치의 수를 알 수 있다.
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
#데이터프레임의 숫자형 열(column)들에 대한 주요 기술 통계량을 요약하여 출력
#평균, 표준편차, 최솟값, 최댓값, 4분위수 등을의 개략적인 데이터 분포도를 확인할 수 있다.
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
#titanic_df에서 'Pclass' 열만 뽑은뒤.
#그 안에 들어있는 값별로 데이터가 몇 개씩 있는지 개수 세기
#그 결과를 value_counts라는 변수에 저장
#DataFrame 이름에 [] 연산자 내부에 칼럼명을 입력하면 series 형태로 특정 칼럼 데이터 세트가 반환된다.
#.value_counts()라는 함ㅅ는 데이터의 분포도를 확인하는데 매우 유용한 함수이다.
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [8]:
#series는 index와 단 하나의 칼럼으로 구성된 데이터 세트(세로줄 한 칸 또는 가로줄 한 칸)
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

In [9]:
#.head() 함수안에 괄호 안에 숫자를 쓰지 않으면 기본적으로 맨 위 5개 행을 출력
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [10]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [11]:
# 1. 데이터프레임의 행(줄) 개수만 출력합니다. (.shape는 (행, 열)이므로 [0]은 행의 개수)
print('titanic_df 데이터 건수:', titanic_df.shape[0])
# 2. 기본값(dropna=True)으로 각 항구별 탑승 인원수를 세어봅니다.
# 'dropna=True'는 "값이 비어있는(NaN) 데이터는 무시하고 세어라"라는 뜻입니다.
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일.
print(titanic_df['Embarked'].value_counts())
# 3. 'dropna=False' 옵션을 주어 다시 인원수를 세어봅니다.
# "값이 비어있는(NaN) 데이터가 있다면 그것도 'NaN'이라는 이름으로 개수를 세어줘!"라는 뜻입니다.
print(titanic_df['Embarked'].value_counts(dropna=False))

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

* 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

In [12]:
import numpy as np
# 표에 붙일 '열 이름'을 리스트로 미리 정해둡니다.
col_name1=['col1']
# 파이썬의 기본 자료형인 1차원 리스트입니다.
list1 = [1, 2, 3]
# 리스트를 넘파이 배열(ndarray)로 변환합니다.
array1 = np.array(list1)
# 1. 넘파이 배열의 모양(Shape) 확인
# 결과: (3,) -> 데이터가 3개 있는 1차원 배열이라는 뜻입니다.
print('array1 shape:', array1.shape )
# 리스트를 이용해 DataFrame 생성.
# pd.DataFrame(데이터, columns=컬럼명리스트) 형식을 사용합니다.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성.
# 리스트와 마찬가지로 ndarray도 데이터프레임의 재료로 바로 쓸 수 있습니다.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)
#이때 index도 추가해주고 싶으면 index = 리스트 형식으로 달면 된다.

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [ ]:
# 3개의 칼럼명이 필요함.(2행 3열짜리 리스트를 쓰기 때문)
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )
df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

In [ ]:
# Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)
# 이때 딕셔너리의 열의 크기는 다 같아야한다. 아니면 생성 못함
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

* DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [15]:
# DataFrame을 ndarray로 변환
# value라는 명령어를 통해 데이터프레임의 인덱스와 칼럼을 싹 떼고 값만 넘파이 배열로 뽑아내기
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [16]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
#to_dict()만 쓰면 이중 딕셔너리로 인덱스를 날려서 나온다
#to_dict('list')를 쓰게되면 리스트안에 인덱스를 쓸 자리가 없어서 인덱스버리고 깔끔하게 나오게된다.
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

### DataFrame의 컬럼 데이터 셋 Access

In [41]:
#데이터프레임에 []를 통해 새로운 칼럼 데이터 세트도 추가할 수 있다
titanic_df['Age_0']=0
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No  Age_0
0            1         0       3  Braund, Mr....    male  12.0      1      0       A/5 21171   7.2500   NaN        S      920.0          2      0
1            2         1       1  Cumings, Mr...  female  28.0      1      0        PC 17599  71.2833   C85        C     1080.0          2      0
2            3         1       3  Heikkinen, ...  female  16.0      0      0  STON/O2. 31...   7.9250   NaN        S      960.0          1      0

In [42]:
#기존 칼럼 series의 데이터를 이용해 새로운 칼럼 series를 만드는 과정
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No  Age_0
0            1         0       3  Braund, Mr....    male  12.0      1      0       A/5 21171   7.2500   NaN        S      120.0          2      0
1            2         1       1  Cumings, Mr...  female  28.0      1      0        PC 17599  71.2833   C85        C      280.0          2      0
2            3         1       3  Heikkinen, ...  female  16.0      0      0  STON/O2. 31...   7.9250   NaN        S      160.0          1      0

In [43]:
#기존 칼럼 데이터도 업데이트를 할수 있다.
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df['Age'] = titanic_df['Age'] - 10


titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No  Age_0
0            1         0       3  Braund, Mr....    male   2.0      1      0       A/5 21171   7.2500   NaN        S      220.0          2      0
1            2         1       1  Cumings, Mr...  female  18.0      1      0        PC 17599  71.2833   C85        C      380.0          2      0
2            3         1       3  Heikkinen, ...  female   6.0      0      0  STON/O2. 31...   7.9250   NaN        S      260.0          1      0

### DataFrame 데이터 삭제

In [ ]:
#.drop() 메서드를 통해 DataFrame에서의 데이터 삭제를 할 수 있다.
# 이때 axis = 1이므로 칼럼방향 축이므로 칼럼을 날릴수 있다.

titanic_drop_df = titanic_df.drop('Age_0', axis=1 )
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No  Age_0
0            1         0       3  Braund, Mr....    male   2.0      1      0       A/5 21171   7.2500   NaN        S      220.0          2      0
1            2         1       1  Cumings, Mr...  female  18.0      1      0        PC 17599  71.2833   C85        C      380.0          2      0
2            3         1       3  Heikkinen, ...  female   6.0      0      0  STON/O2. 31...   7.9250   NaN        S      260.0          1      0

In [ ]:
#drop() 메서드는 디폴트 값으로 inplace값이 False로 되어있기 때문에 원본 데이터는 안날아간다.
# 따라서 다음 표를 보면 Age_0이라는 칼럼이 살아있는 것을 볼 수 있다.
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

In [ ]:
# inplace = True로 만들어주게 되면 원본데이터를 바꿔버린다.
# inplace = True를 통해 데이터프레임을 수정하게되면 원본데이터를 바꾸고 아무것도 반환하지않게된다.
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(' inplace=True 로 drop 후 반환된 값:',drop_result)
titanic_df.head(3)

 inplace=True 로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
# 로우 데이터 지우기 여러 행을 지우고 싶을때는 리스트로 감싸고 axis=0을 통해 행을 지우고 inplace = True로 원본 데이터를 수정하는 것
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

### Index 객체

In [61]:
# 원본 파일 재 로딩 
titanic_df = pd.read_csv('titanic_train.csv')
# Index 객체 추출
indexes = titanic_df.index
print(indexes)
#Index 객체를 실제 값 array로 변환
print('Index 객체 array값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [ ]:
#.value로 값을 뽑으면 넘파이 ndarray형태로 변환
# 1차원 넘파이로 나옴.
# 슬라이싱과 단일 값 반환 전부 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [ ]:
# 한 번 만들어진 DataFrame 및 Series의 Index 객체는 함부로 변경할 수 없다.
# 데이터프레임에서 인덱스는 단순한 숫자가 아니라, 각 데이터가 어디에 있는지 알려주는 절대적인 주소이기 때문.
indexes[0] = 5

TypeError: Index does not support mutable operations

In [ ]:
# Fare 열만 떼서 series를 생성
series_fair = titanic_df['Fare']
# Fare 열의 최대, 합을 구할 수 있꼬 파이썬 기본함수인 sum도 쓸수 있다.
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
# +3을 하게되면 각 행마다 자동으로 3씩 더해준다.
print('Fair Series + 3:\n',(series_fair + 3).head(3) )

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

In [ ]:
# .reset_index()를 통해 새롭게 index를 연속 숫자 형으로 할당할 수 있다. (inplace=False)는 아까 말했듯이 원본을 건드리지 않겠다는 것이다.
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [ ]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))

# 그냥 value.counts()를 하게되면 value가 많은 순서대로 내림차순 정렬을 하는데 reset_index를 통해 데이터 프레임으로 반환할 수 있다.
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

### 데이터 셀렉션 및 필터링

* DataFrame의 [ ] 연산자

In [ ]:
print('단일 컬럼 데이터 추출:\n', titanic_df[ 'Pclass' ].head(3))
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived', 'Pclass'] ].head(3))
# []안에는 칼럼명이나 인덱스 형태로 변환 가능한 표현식이 들어가야하므로 오류가 난다.
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 컬럼들의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [ ]:
# 슬라이싱을 하면 행을 뽑을 수 있다.
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [69]:
# 불린 인덱싱 표현도 가능하다 'Pclass' 열에 3인 행을 위에서 3개뽑기
titanic_df[ titanic_df['Pclass'] == 3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

* DataFrame iloc[ ] 연산자

In [ ]:
# 딕셔너리를 데이터프레임으로 변환하는 과정
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [ ]:
# 1행 1열자리에 있는 데이터를 뽑아낸다.
data_df.iloc[0, 0]

'Chulmin'

In [72]:
# 아래 코드는 오류를 발생시킵니다.
# iloc은 위치기반 인덱싱 방식이므로 명칭을 넣으면 안된다.
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [73]:
# 아래 코드는 오류를 발생합니다.
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [ ]:
# 넘파이 인덱싱과 마찬가지로 -1은 맨 마지막 데이터 값이고 :는 모든 데이터 값을 의미한다.
print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n", data_df.iloc[: , :-1])

 맨 마지막 칼럼 데이터 [:, -1]
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1]
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015

* DataFrame loc[ ] 연산자

In [ ]:
# loc는 명칭기반 인덱싱이라 이름을 정확히 넣어줘야한다.
data_df.loc['one', 'Name']

'Chulmin'

In [76]:
# 아래 코드는 오류를 발생합니다.
# 0과 같은 위치기반으로 인덱싱을 하면 오류가 난다 
data_df_reset.loc[0, 'Name']

NameError: name 'data_df_reset' is not defined

In [ ]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n')
# loc 슬라이싱은 명칭기반이므로 슬라이싱할때 'two'까지 슬라이싱을한다.
# 또한 loc 슬라이싱은 iloc과 달리 불린 인덱싱이 된다.
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name'])

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

* 불린 인덱싱

In [79]:
titanic_df = pd.read_csv('titanic_train.csv')
# 불린 인덱싱을 통해 Age 열에 value값이 60이 넘는 행들만 불러오는 과정
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [ ]:
# 불린 인덱싱으로 60세보다 많은 데이터 뽑고 Name, Age 열만 따로 뽑는 과정
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [ ]:
# loc를 이용해서 동일하게 데이터를 뽑는 방법
titanic_df.loc[titanic_df['Age'] > 60, ['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [ ]:
# 여러 개의 복합조건을 나타낼때 [조건1][조건2][조건3]을 써도 되지만 []안에 괄호로 다같이 써도 된다. 
# 복한 조건 연산자 and는 &로 쓰고 or 조건일때는 |, not 조건일때는 ~를 쓰면 된다.
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [ ]:
# 개별 조건을 변수에할당하고 이들 변수를 결합해서 불린 인덱싱을 수행할 수도 있다.
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[ cond1 & cond2 & cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

### 정렬, Aggregation함수, GroupBy 적용

* DataFrame, Series의 정렬 - sort_values()

In [ ]:
# .sort_values()를 통해 dataframe을 정렬할 수 있다
# by로 특정 칼럼을 입력하면 해당 칼러므로 정렬을 수행한다.
# ascending = True를 설정하면 오름차순이고 ascending = False를 설정하게 되면 내림차순으로 정렬이 된다, 디폴트 값으로 ascending = True가 되어있다.
# implace = True로 하면 원본 dataframe을 바꾸며 디폴트는 False로 되어있다.
# sort_values()안에 by=name이므로 Name이라는 열에서 오름차순으로 정렬이 된다. 
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [88]:
#여러 항목도 불러올수 있으며, ascending=False로 하였기 때문에 내림차순으로 정렬이 된다.
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

* Aggregation 함수 적용
>>>Aggregation 함수란 집계(aggregation) 함수로 여러 개의 데이터를 뭉쳐서 딱 하나의 대표 결과값으로 나타내주는 함수

In [ ]:
# count()를 적용하게되면 어느 항목에 결측치가 있는지 알아보기 쉽다.
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
# Age와 Fare열의 평균을 나타내기위해 mean()을 쓴다;.
titanic_df[['Age', 'Fare']].mean()

Age     21205.1700
Fare    28693.9493
dtype: float64

* groupby() 이용하기

In [ ]:
# groupby()를 통해서 pclass에 있는 같은 데이터 별로 묶을 수 있다.
# 인덱스를 원하는걸로 만들어서 정리하는 느낌?
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [98]:
# groupby() 를 호출해 반환된 결과에 aggregation 함수를 적용하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수를 적용한다.
titanic_groupby = titanic_df.groupby(by='Pclass').count()

titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [ ]:
# 원하는 칼럼만 뽑아서 aggregation을 할 수도있다.
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [ ]:
# pclass로 groupby하고 age열만 뽑아서 최대 최소값 뽑는 과정 
# agg()를 통해 aggregation 함수를 여러개 적용할 수 있다.
# groupby를 여러가지로 항목으로 묶을수 있다.
titanic_df.groupby(['Pclass', 'Sex'])['Age'].agg([max, min])

C:\Users\Sanghyeon\AppData\Local\Temp\ipykernel_27992\2965875724.py:3: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby(['Pclass', 'Sex'])['Age'].agg([max, min])
C:\Users\Sanghyeon\AppData\Local\Temp\ipykernel_27992\2965875724.py:3: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby(['Pclass', 'Sex'])['Age'].agg([max, min])

                max   min
Pclass Sex
1      female  63.0  2.00
       male    80.0  0.92
2      female  57.0  2.00
       male    70.0  0.67
3      female  63.0  0.75
       male    74.0  0.42

In [ ]:
# agg() 안에 딕셔너리를 통해서 각각 열에대한 계산을 다르게 할 수 있다.
# 나이는 최댓값, sibsp는 총합, Fare는 평균으로 계산하는 과정
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기
* isna()로 결손 데이터 여부 확인

In [ ]:
# inna()를 통해 결손값이 있는지의 여부를 알수 있다.
titanic_df.isna().head(3)

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0          False     False   False  False  False  False  False  False   False  False   True     False
1          False     False   False  False  False  False  False  False   False  False  False     False
2          False     False   False  False  False  False  False  False   False  False   True     False
3          False     False   False  False  False  False  False  False   False  False  False     False
4          False     False   False  False  False  False  False  False   False  False   True     False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...    ...    ...       ...
886        False     False   False  False  False  False  False  False   False  False   True     False
887        False     False   False  False  False  False  False  False   False  False  False     False
888        False     False   False  False  False   True  False  False   False  False   True     False
889        False     False   False  False  False  False  False  False   False  False  False     False
890        False     False   False  False  False  False  False  False   False  False   True     False

[891 rows x 12 columns]

In [110]:
# sum()을 호출 시 True는 내부적으로 숫자 1로, Falsesms 숫자 0으로 변환되므로 결손 데이터의 개수를 구할 수 있다.
# 이때 sum()은 디폴트 값이 axis = 0 이므로 세로로 쭉 훑으면서 더한다
# sum(axis = 1)을 하게 되면 행의 결측값 수를 구할 수 있다.
titanic_df.isna( ).sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

* fillna( ) 로 Missing 데이터 대체하기

In [ ]:
# fillna()로 결손값을 대체할 수 있다.
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [ ]:
# Age 칼럼의 결손값을 평균 나이로
# Embarked 칼럼의 결손값을 s로 대체하는 과정
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### apply lambda 식으로 데이터 가공

In [113]:
# 입력값의 제곱 값을 구해서 반환하는 get_square(a)ㄹ는 함수를 만들기
def get_square(a):
    return a**2

print('3의 제곱은:',get_square(3))

3의 제곱은: 9

In [ ]:
# lambda로도 같은 함수를 만들어서 배출할 수 있다.
lambda_square = lambda x : x ** 2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9

In [119]:

a=[1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [ ]:
# Name_len이라는 새로운 열을 만들고
# Name열을 따로 떼서 이름 길이를 하나하나씩 가져와서 열을 채운다
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [123]:
# child_Adult라는 새로운 열을 만들고 
# Age열의 데이터값이 15이하이면 child를 내고 아니면 Adult를 내어 열을 채운다.
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' )
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [124]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 
                                                                                  'Elderly'))
titanic_df['Age_cat'].value_counts()

Age_cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

In [125]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성. 
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'
    
    return cat

# lambda 식에 위에서 생성한 get_category( ) 함수를 반환값으로 지정. 
# get_category(X)는 입력값으로 ‘Age’ 컬럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult